preprocessing:
  input_convertor: 'nn_vectorization'      
  predefined_embedding_path: './data/glove.twitter.27B.100d_min.txt'
  use_predefined_embedding: true
training:
  model_name: 'textgrucnn'
  learning_rate: 0.01
  embedding_dim: 128  
  epochs: 1  
predict:
  output_path: ./data/submission_gru.csv