preprocessing:
  input_convertor: 'nn_vectorization'
  maxlen: 32  
  use_predefined_embedding: false
  predefined_embedding_path: './data/embedding_min.csv'
training:
  model_name: 'textrnn'
  learning_rate: 0.7
  embedding_dim: 100  
  epochs: 3

