preprocessing:
  input_convertor: 'nn_vectorization'
  maxlen: 128  
  use_predefined_embedding: false
  predefined_embedding_path: './data/embedding_min.csv'
training:
  model_name: 'textrnn'
  learning_rate: 0.01
  embedding_dim: 128  
  epochs: 3
predict:
  output_path: ./data/submission_rnn.csv

